//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessangerClient.Messang {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Messang.IMessenger", CallbackContract=typeof(MessangerClient.Messang.IMessengerCallback))]
    public interface IMessenger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Login", ReplyAction="http://tempuri.org/IMessenger/LoginResponse")]
        void Login(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Login", ReplyAction="http://tempuri.org/IMessenger/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/SendMessage", ReplyAction="http://tempuri.org/IMessenger/SendMessageResponse")]
        void SendMessage(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/SendMessage", ReplyAction="http://tempuri.org/IMessenger/SendMessageResponse")]
        System.Threading.Tasks.Task SendMessageAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Logout", ReplyAction="http://tempuri.org/IMessenger/LogoutResponse")]
        void Logout(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessenger/Logout", ReplyAction="http://tempuri.org/IMessenger/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessengerCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IMessenger/TextForUsers")]
        void TextForUsers(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessengerChannel : MessangerClient.Messang.IMessenger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessengerClient : System.ServiceModel.DuplexClientBase<MessangerClient.Messang.IMessenger>, MessangerClient.Messang.IMessenger {
        
        public MessengerClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public MessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public MessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public MessengerClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string name) {
            base.Channel.Login(name);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string name) {
            return base.Channel.LoginAsync(name);
        }
        
        public void SendMessage(string text) {
            base.Channel.SendMessage(text);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string text) {
            return base.Channel.SendMessageAsync(text);
        }
        
        public void Logout(string name) {
            base.Channel.Logout(name);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string name) {
            return base.Channel.LogoutAsync(name);
        }
    }
}
